### ISSUE TITLE
4.8 Version?

### ISSUE THREAD

**Issue by azarus** [fmod/ue4integration#1]
Can we have the 4.8 binary versions please?

**Comment by Liberte78** [comment]
I'm also looking forward to it. Please :)

**Comment by fmod-geoff** [comment]
We have added source code with 4.8 support here in github.  Be aware there is an issue with 4.8 which is mentioned here:

http://www.fmod.org/questions/question/support-for-ue4-4-8

We will do a binary release hopefully by the end of this week, unless we find any other issues with 4.8.

**Comment by Liberte78** [comment]
Thnx for the info!

**Comment by Frezer** [comment]
Still no binary version for 4.8? :-(

**Comment by azarus** [comment]
MachineId:746E39B041147C003DA7D8A67F35CA1C
EpicAccountId:40dd2988f279471f82aefa4031bd2e82

Access violation - code c0000005 (first/second chance not available)

""

LibOVRRT64_0_6
LibOVRRT64_0_6
LibOVRRT64_0_6
LibOVRRT64_0_6
LibOVRRT64_0_6
UE4Editor_OculusRift!FOculusRiftHMD::InitDevice()
UE4Editor_OculusRift!FOculusRiftHMD::Startup()
UE4Editor_OculusRift!FOculusRiftHMD::FOculusRiftHMD()
UE4Editor_OculusRift!FOculusRiftPlugin::CreateHeadMountedDisplay()
UE4Editor_Engine!UEngine::InitializeHMDDevice() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\engine\private\unrealengine.cpp:1839]
UE4Editor_Engine!UEngine::Init() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\engine\private\unrealengine.cpp:739]
UE4Editor_UnrealEd!UEditorEngine::InitEditor() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\editor\unrealed\private\editorengine.cpp:425]
UE4Editor_UnrealEd!UEditorEngine::Init() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\editor\unrealed\private\editorengine.cpp:580]
UE4Editor_UnrealEd!UUnrealEdEngine::Init() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\editor\unrealed\private\unrealedengine.cpp:48]
UE4Editor!FEngineLoop::Init() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\launchengineloop.cpp:2026]
UE4Editor_UnrealEd!EditorInit() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\editor\unrealed\private\unrealed.cpp:63]
UE4Editor!GuardedMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\launch.cpp:133]
UE4Editor!GuardedMainWrapper() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.8\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]

**Comment by azarus** [comment]
Can we have the 4.8 binary versions please? Anything that just doesn't crash is helpfull. Also the issue you're linking to isn't working. I don't have access to that link. (Awesome fail)

**Comment by fmod-geoff** [comment]
I'm not sure which link you mean isn't working.  Do you mean the link the FMOD Q/A or the link witin that to the Epic UDN post?

As for a release.  We would like to do a release tomorrow, but there is currently an issue with mac binaries that the commandline approach (building via runuat) produces a binary plugin that produces an error at initialization time.  If I can get to the bottom of that tonight or tomorrow we'll be good for a build, otherwise I'll update with more information.

I'm not sure what the crash log above indicates.  Once we get a build out we can look into it more.

**Comment by azarus** [comment]
The UDN post. ó

**Comment by fmod-geoff** [comment]
Windows version is good but the Mac .dylib loading is broken in 4.8, investigating more now.

**Comment by fmod-geoff** [comment]
Finally have a binary release available at http://www.fmod.com/download
