### ISSUE TITLE
Can you create example for cocos2d-x

### ISSUE THREAD

**Issue by KAMIKAZEUA** [fmod/ue4integration#10]
Most popular open-source 2D game engine in a world https://github.com/cocos2d/cocos2d-x

Why there is no any simple 2d example from you?

**Comment by fmod-cameron** [comment]
https://github.com/fmod/EarthWarrior3D

**Comment by KAMIKAZEUA** [comment]
Thats for 3D which is just experimental for cocos2d-x. So not useful. Also its not been updated a couple of years already. 

Why you so ignore this? I want example for latest cocos2d-x.
