### ISSUE TITLE
[UE4.16] Crash in packaged game

### ISSUE THREAD

**Issue by Kyoril** [fmod/ue4integration#12]
As described here (https://www.fmod.org/questions/question/eta-for-fmod-for-ue-4-16/#sabai-entity-content-46100), my game crashes in packaged builds on startup (editor and launch from editor works fine).

I tried several things and it turned out, that I do this in my default game mode's constructor:
`(void)IFMODStudioModule::Get();`

I do this, because in the past, when I didn't do this, FMOD events from my character blueprint (which gets loaded in the game mode's constructor as well, wouldn't play as they are simply not yet available on blueprint construction then.

This worked well in the past, but now crashes (because when I uncomment the line mentioned above, everything runs without a crash, but AGAIN: The fmod events in my character blueprint won't play.

What is the best/recommended way of handling this?

**Comment by Kyoril** [comment]
Note: I have a workaround in place. The thing is, that the constructor of my game mode gets called on package load somehow. What I do now is to override the InitGame method and set the DefaultPawnClass there (including the `(void)IFMODStudioModule::Get();` part just above) and calling `Super::InitGame(...)` afterwards.

This feels very hacky and I'm really not happy with this solution, but it works for now (no crash AND everything playing in packaged builds).

I still would be happy about an investigation on the crash.

**Comment by homembarata** [comment]
I'm having the exact same problem, tried your solution but I don't understand how to set DefaultPawnClass  out of the constructor, I'm using ConstructorHelpers::FClassFinder to get the pawn from a blueprint and it doesn't work out of it.

Have you found a better solution? I've just spent a whole day stuck on this :/

**Comment by fmod-cameron** [comment]
This is documented on our UE4 Deployment page of the docs:
https://fmod.com/resources/documentation-api?page=content/generated/engine_ue4/deployment.html#/
Under heading 'Loading blueprints before plugin load'.
