### ISSUE TITLE
Version 1.10.00 doesn't build under UE4 1.17.2

### ISSUE THREAD

**Issue by Nagell** [fmod/ue4integration#20]
Without "Binaries" directory FMOD version 1.10.00 doesn't build. With them all works perfect but it's still very big amount of data for our repository.

**Comment by fmod-cameron** [comment]
I'm not sure exactly what you mean, could you please expand?
Are you talking about the Binaries folder in the plugin?

**Comment by Nagell** [comment]
Yes indeed. I'm not able to add to our repository a plugin without Binaries folder, because without it the plugin stops working, and Visual 2015 is not able to build it. So there are two possibilities:
- light for repo but not working
- heavy and workking

**Comment by Dico200** [comment]
You can't do anything without the dependencies that are contained in the binaries folder. 

If you want to reduce the size, you can remove all folders inside Binaries/ with the exception of your own operating system. In windows 10 for example, assuming your machine is 64 bit, you can delete all but Win64 directory.

I am no representative of fmod or the plugin, but common logic tells me that this is something you can try.

**Comment by Nagell** [comment]
I just fought that binaries should be build from project. Whats the purpose of building if binaries are also needed? Wouldn't it be easier using only building or only ready binaries, or even better, as plugin (ready to use)?
