### ISSUE TITLE
Wrong version label in UE4

### ISSUE THREAD

**Issue by Nagell** [fmod/ue4integration#21]
Version 1.10.00 is visible in UE4 4.17.2 as 1.09.06 so it's a bit misleading.

![image](https://user-images.githubusercontent.com/4633237/31565399-f20068d6-b066-11e7-803e-100ac44f3bc5.png)

![image](https://user-images.githubusercontent.com/4633237/31565413-05f8dd00-b067-11e7-864b-7c10572ecf68.png)

**Comment by fmod-cameron** [comment]
This should not have any effect on the project, but I can understand the annoyance.
This has already been fixed for the next release. Thanks!
