### ISSUE TITLE
Is this proyect active?

### ISSUE THREAD

**Issue by Daverkex** [fmod/ue4integration#26]
I know that FMOD update this proyect with news releases of Unreal Engine 4 but the issues and PR's of this project have remained opened for many time, and unanswered.

FMOD continue mantain actively this repo?

**Comment by fmod-cameron** [comment]
Apologies for the delayed response.
We generally use this repo to give out minor fixes between our regular releases.

If you have an issue or suggestion, it is generally best to use our Q&A
http://www.fmod.org/support/qa/
