### ISSUE TITLE
[UE4.18] Packaged Game Crashes

### ISSUE THREAD

**Issue by NotMickey** [fmod/ue4integration#27]
My UE4 project uses FMOD Audio banks which work properly and play when I run my project from the Editor.
However on packaging my project for deployment and playing I get the following error
![screenshot 30](https://user-images.githubusercontent.com/31252662/37562832-44634dba-2a37-11e8-90cd-44706d931c29.png)

This started to happen when i included the **IFMODStudioModule::Get();**  above the class finder in the gamemode.cpp file (As detailed in the deployment documentation for UE4).

Before doing that the packaged project would run fine but the sounds attached to the player blueprint would not play (there is no impact on the rest of the sounds in my project).

I am honestly at my wits end by this point. Any help would be appreciated.

EDIT: Added LogFile for reference
[GameFile.log](https://github.com/fmod/ue4integration/files/1823480/AndIMustScream.log)

**Comment by fmod-cameron** [comment]
Was this using the integration from here or the download from our website?
(This one wasn't up to date)

**Comment by NotMickey** [comment]
This was from the integration downloaded from the fmod website.

**Comment by fmod-cameron** [comment]
I believe this is caused by a change made to the FMODStudioModule::Get() function, this should fix it:
https://github.com/fmod/ue4integration/commit/2d5564e29d02112b96994f82c5fee72f32b317d4

**Comment by NotMickey** [comment]
I don't have access to my work station right now, but I will try it out first thing tomorrow!

**Comment by Dec1234** [comment]
Hey. Also getting this issue on 4.19. (Recently upgraded from 4.15 but with a fresh FMOD plugin)

Also occurring inside the Game Mode class. same exact line in _AsyncLoading.cpp_. I also have the latest FMOD 4.19 plugin version from a couple of days ago.

I already had a **FMODStudioModule::Get()** in the constructor of my GameMode, and also the Pawn class that is being loaded by the GameMode that gets this crash. It only happens on the shipping build, no issues in the editor.


Current solution is to manually load the player class elsewhere other than the GameMode class, but this makes some functionality for getting the default pawn class on client's a little messy.

**Comment by NotMickey** [comment]
Wow, that actually worked! Thanks a lot!

Anyway, I too hope this doesn't cause problems down the line, but for now the problem is solved.

**Comment by NotMickey** [comment]
I'm actually gonna leave this issue open for now.

**Comment by moadib** [comment]
Look at `FindOrConstructDynamicTypePackage` code in UE4, maybe this is how it should be done?
```
Package = CreatePackage(nullptr, PackageName);
if (!GEventDrivenLoaderEnabled)
{
	Package->SetPackageFlags(PKG_CompiledIn);
}
```
