### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by Banbury** [fmod/ue4integration#3]
I have installed the FMOD plugin into a new empty project (UE 4.8.2). I opened it and pressed 'Play' in the editor.

It printed hundreds of times the same error message, eventually freezing the game and the editor:

LogFMOD:Error: 'StudioSystem[EFMODSystemContext::Runtime]->update()' returned 'A socket error occurred.  This is a catch-all for socket-related errors not listed elsewhere.'

System: Win7 x64, 8MB Ram, 4 cores

**Comment by Banbury** [comment]
After some more testing I found the culprit.
When I turn off Live Update in the project settings, it works.

**Comment by fmod-geoff** [comment]
Thanks, it would be good to have a better error message for this.  But for now I'll just close this issue.

**Comment by Banbury** [comment]
So, how to make it work with Live Update enabled? There's still a bug here, you know.

**Comment by fmod-geoff** [comment]
The error will be because some other application is using the default port that FMOD wants to use.  We'll expose the port as an advanced setting so you will be able to get around this and choose a different port that works on your system.

**Comment by fmod-geoff** [comment]
If you run into this problem again, you can now set the live update port in the UE4 FMOD settings window.  

To connect via Studio, you can enter the IP address and the port, so if you chose 3300 as the port you would connect via "localhost:3300"
