### ISSUE TITLE
cannot find -lfmodL ... cannot find -lfmodstudioL

### ISSUE THREAD

**Issue by brothermechanic** [fmod/ue4integration#37]
Hello
I found a way to compile ue4 plugins by this tuto https://youtu.be/kZqVeD_r0Ow
- create c++
- compile plugin
- .../GenerateProjectFiles.sh TestProject.uproject
- make TestProjectEditor
log
https://hastebin.com/esepudiguf.md
Give me an adwice, what i need to install, or something else?

**Comment by fmod-cameron** [comment]
The libs are not included in this repository, you will have to download them separately from https://fmod.com/download
