### ISSUE TITLE
custom file read function please! 

### ISSUE THREAD

**Issue by RPG3D** [fmod/ue4integration#46]
we need packaging all files into pak files(or other custom file format), so there should be a methd to call myself file reading logic

**Comment by fmod-cameron** [comment]
I'm not sure what you mean sorry, can you elaborate on what it is that you require?

**Comment by RPG3D** [comment]
> I'm not sure what you mean sorry, can you elaborate on what it is that you require?

I want to use a custom file package format, WOW's MPQ file for example, the FMOD assets will be package into the package file.

**Comment by fmod-derek** [comment]
There are already hooks in the FMOD Core API for using a custom file system - see the documentation for FMOD::System::setFileSystem. The UE4 integration uses this API to have FMOD use the Unreal file system.

We don't think it makes sense to add another layer of hooks in the UE4 integration to support custom file systems from the integration, if you'd like to keep your data files in a custom file system please fork and modify the integration source code.
