### ISSUE TITLE
FMODStudio Plugin 2.00.06 crashes when opening Unreal Editor 4.24.1 "Help" menu!

### ISSUE THREAD

**Issue by TheBUCH** [fmod/ue4integration#49]
![FMODStudio plugin exception issue](https://user-images.githubusercontent.com/27789215/71684518-5f967500-2d9e-11ea-97b1-92143c03cb48.png)

Also, the **FMODStudio.uplugin** file contains:
`	"Version" : 20007,
	"VersionName" : "2.00.07",`
Even though I clearly selected **2.00.06** from the website downloads (there isn't even an option for 07 at the time of writing), what's up with that?

Side note: It's a Windows build, by the way. But it doesn't even reach `#if PLATFORM_WINDOWS` in `void FFMODStudioEditorModule::AddHelpMenuExtension(FMenuBuilder &MenuBuilder)`, so doesn't matter.

**Comment by fmod-cameron** [comment]
The fix for this will be out in the next release, I have also added to a branch for UE4.24, https://github.com/fmod/ue4integration/commit/db6c182c3f7aa6ec3789799717e6723b5263e5dc
