### ISSUE TITLE
Unreal 4.24 FMOD warning in Build.cs 

### ISSUE THREAD

**Issue by emaovo** [fmod/ue4integration#53]
This is the warning I get when building for 4.24 
I'm afraid that if Epic deletes the currently obsolete variables, FMOD will not build in 4.25.

FMODStudio.Build.cs(133,17): warning CS0618: 'UnrealBuildTool.ModuleRules.PublicLibraryPaths' is obsolete: 'For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths'
FMODStudio.Build.cs(134,17): warning CS0618: 'UnrealBuildTool.ModuleRules.PublicLibraryPaths' is obsolete: 'For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths'
FMODStudio.Build.cs(135,17): warning CS0618: 'UnrealBuildTool.ModuleRules.PublicLibraryPaths' is obsolete: 'For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths'
FMODStudio.Build.cs(176,13): warning CS0618: 'UnrealBuildTool.ModuleRules.PublicLibraryPaths' is obsolete: 'For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths'

**Comment by fmod-cameron** [comment]
Thanks for the heads up, we are aiming to have this resolved for an upcoming release.
