### ISSUE TITLE
Category Tags on Properties

### ISSUE THREAD

**Issue by andrew-nocode** [fmod/ue4integration#58]
FMODAssetLookup and FMODBankLookup have a few UPROPERTIES and they because they don't have Category tags they prevent the plugin being used as an engine plugin.

a change like this would allow the plugin to be used as an engine plugin.

`- UPROPERTY(EditAnywhere, BlueprintReadOnly)`
`+ UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "FMOD")`

**Comment by fmod-derek** [comment]
Thanks for reporting this, we'll update the specifiers on those properties and make sure the integration can be used as an engine plugin.
