### ISSUE TITLE
Missing some properties/functions references with last commit on branch 4.26

### ISSUE THREAD

**Issue by gabuscuv** [fmod/ue4integration#63]
Trying to compile the commit 511e9fa56b77ee2160f7b876a31e2339f698bf8f, (last commit from branch 2.01-UE4.26)
There are some Error Compilations because the property "GeneratedFolders" (maybe "Path" too?) and the function "GetFullContentPath" It's missing from UFMODSettings,
(referenced by FMODStudio/Source/FMODStudioEditor/Classes/FMODGenerateAssetsCommandlet.h & FMODStudio/Source/FMODStudioEditor/Private/FMODGenerateAssetsCommandlet.cpp)

I think is from these files:
Plugins\FMOD\FMODStudio\Source\FMODStudio\Classes\FMODSettings.h
Plugins\FMOD\FMODStudio\Source\FMODStudio\Private\FMODSettings.cpp

Could you check if you forgot add some files to the last commit?

Of Course, Take your time and Thanks for all

(Of course, I will roll back (my copy cloned as submodule from my repo, I mean) the commit until it's fixed)

Building compilation info:
```
   [1/4] FMODGenerateAssetsCommandlet.cpp

    Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\FMODGenerateAssetsCommandlet.cpp(42): error C2039: 'GeneratedFolders': is not a member of 'UFMODSettings'

   Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\../Classes/FMODAssetBuilder.h(17): note: see declaration of 'UFMODSettings'

    Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\FMODGenerateAssetsCommandlet.cpp(42): error C2143: syntax error: missing ';' before ':'

   Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\FMODGenerateAssetsCommandlet.cpp(42): error C2143: syntax error: missing ';' before ')'

    FMOD\FMODStudio\Source\FMODStudioEditor\Private\FMODGenerateAssetsCommandlet.cpp(44): error C2039: 'Path': is not a member of 'FString'

    Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\FMODGenerateAssetsCommandlet.cpp(55): error C2039: 'GetFullContentPath': is not a member of 'UFMODSettings'

    Plugins\FMOD\FMODStudio\Source\FMODStudioEditor\Private\../Classes/FMODAssetBuilder.h(17): note: see declaration of 'UFMODSettings'
```

EDIT: Fixing Building log format

**Comment by fmod-cameron** [comment]
Apologies, I also realized this over the weekend. This has been fixed now.
