### ISSUE TITLE
Patch: Trigger Delegate callback when programmer sound stops

### ISSUE THREAD

**Issue by sirjofri** [fmod/ue4integration#73]
[FMODAudioComponent.cpp.txt](https://github.com/fmod/fmod-for-unreal/files/9887496/FMODAudioComponent.cpp.txt)
[FMODAudioComponent.h.txt](https://github.com/fmod/fmod-for-unreal/files/9887497/FMODAudioComponent.h.txt)

These two attached patches add a new Unreal delegate `OnSoundStopped` that's triggered when a programmer sound finishes playing but the event is still playing.

In our setup we start an event with programmer sounds (from an audio table) for each dialogue line, and we want to get notified when the currently playing dialogue line ends. This patch allows us to bind to that new delegate and get notified about that.

Note that there are a few comments in the patches you surely want to adjust.

Thank you

**Comment by ConnorY97** [comment]
Hi, I have passed this on to our dev team to look into further. Thank you for the suggestion!

**Comment by Connor-FMOD** [comment]
Hi,

Thank you for the suggestion, I have passed it onto our development team to look into further.

**Comment by sirjofri** [comment]
This change seems to be added to the latest 5.1 version, if I see that correctly? Guess we can close this ticket then...

**Comment by Connor-FMOD** [comment]
Hi, 

Yes, your suggestions were added in the latest update. The ticket can be closed.
