### ISSUE TITLE
'AVAudioSessionInterruptionWasSuspendedKey' is deprecated FMOD for Unreal 2.0.2.20 for iOS

### ISSUE THREAD

**Issue by davaidev** [fmod/ue4integration#79]
Hi guys, I have Xcode 15.2 + MacOS Sonoma 14.2.1 + iPhone SDK 17.2  + Apple M3 chip

When I build my project with FMOD for Unreal 2.0.2.20 for iPhone 15 Pro iOS 17.2.1 i have this warning

[698/733] Compile [arm64] FMODStudioModule.cpp
/Plugins/FMODStudio/Source/FMODStudio/Private/FMODStudioModule.cpp:1573:61: warning: 'AVAudioSessionInterruptionWasSuspendedKey' is deprecated: first deprecated in iOS 14.5 - No longer supported - see AVAudioSessionInterruptionReasonKey [-Wdeprecated-declarations]
                    if ([[notification.userInfo valueForKey:AVAudioSessionInterruptionWasSuspendedKey] boolValue])
                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AVFAudio.framework/Headers/AVAudioSession.h:654:27: note: 'AVAudioSessionInterruptionWasSuspendedKey' has been explicitly marked deprecated here
OS_EXPORT NSString *const AVAudioSessionInterruptionWasSuspendedKey API_DEPRECATED("No longer supported - see AVAudioSessionInterruptionReasonKey", ios(10.3, 14.5), watchos(3.2, 7.3), tvos(10.3, 14.5));
                          ^
1 warning generated.

I think FMOD team need to fix it

**Comment by fmod-cameron** [comment]
This has been fixed in version 2.02.21.
