### ISSUE TITLE
FMODStudioOculus could not be found

### ISSUE THREAD

**Issue by Filippoml** [fmod/ue4integration#8]
![cattura](https://cloud.githubusercontent.com/assets/14567796/23720062/e26a0fd8-043d-11e7-812a-2db9a397f5b9.PNG)
Unreal Engine Version 4.15.0

**Comment by fmod-cameron** [comment]
That just means there was an error compiling the plugin, the FMODStudioOculus module is the first one it encounters so it throws that error. If you compile the project from source it should give you a more detailed error.
